version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata /data.json && gunicorn reservations.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/src/reservations/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
        main:
            aliases:
                - app
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=reservations_database
      - POSTGRES_USER=reservations_user
      - POSTGRES_PASSWORD=password
    networks:
        main:
            aliases:
                - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/src/reservations/static/
    links:
      - app:app
    ports:
      # 8042 is set in apache to forward it from :80
      - "8042:80"
    depends_on:
      - app
    networks:
        main:
            aliases:
                - nginx
networks:
  main:

volumes:
  postgres_data:
  static_volume:
