version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./:/app

    depends_on:
      - app
  app:
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - ./:/app
      - ./static:/static/

    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=reservations_database
      - DB_USER=reservations_user
      - DB_PASS=test
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=reservations_database
      - POSTGRES_USER=reservations_user
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
