# Generated by Django 3.2.9 on 2021-11-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.building')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.group')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Pending authorisation', 'Pending authorisation'), ('Expired', 'Expired')], default='Pending authorisation', max_length=32)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_from', models.DateTimeField()),
                ('dt_to', models.DateTimeField()),
                ('dt_created', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='attendee', to='reservations.User')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='reservations.user')),
                ('reservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationstatus')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.room')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='subgroup',
            field=models.ManyToManyField(related_name='_reservations_group_subgroup_+', to='reservations.Group'),
        ),
    ]
