# Generated by Django 3.2.9 on 2021-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationstatus',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupy',
            field=models.ManyToManyField(related_name='occupies', to='reservations.Room'),
        ),
    ]
