# Generated by Django 3.2.9 on 2021-12-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_group_manager', 'Can manage group'), ('is_room_manager', 'Can manage room'))},
        ),
    ]
