# Generated by Django 3.2.9 on 2021-11-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupy',
            field=models.ManyToManyField(blank=True, related_name='occupies', to='reservations.Room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendee', to='reservations.Person'),
        ),
        migrations.AlterField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.person'),
        ),
    ]
