# Generated by Django 3.2.9 on 2021-11-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_group_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subgroup',
            field=models.ManyToManyField(blank=True, to='reservations.Group'),
        ),
    ]
