# Generated by Django 3.2.9 on 2021-11-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_group_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.group'),
        ),
    ]
