# Generated by Django 3.2.9 on 2021-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_room_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.ManyToManyField(blank=True, related_name='res_status', to='reservations.ReservationStatus'),
        ),
    ]
