# Generated by Django 3.2 on 2021-11-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20211123_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.group'),
        ),
    ]
